# Generated by Django 4.2.2 on 2023-10-31 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.PositiveBigIntegerField(),
        ),
    ]
