# Generated by Django 4.2.2 on 2023-11-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_employees_age_alter_employees_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='image',
            field=models.ImageField(null=True, upload_to='assests/emp_img'),
        ),
    ]
