# Generated by Django 4.2.2 on 2023-11-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_employees_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
        migrations.AddField(
            model_name='employees',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
